- name: Create a new EC2 Instance
  ec2:
    key_name: "{{ key_name }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    wait: true
    group: "{{ security_group }}"
    count: 1
    vpc_subnet_id: "{{ subnet }}"
    assign_public_ip: yes
    region: "{{ region }}"
    instance_tags: 
      Name: webserver
      Software: nginx
  register: ec2

- name: Attach instance role
  shell: "aws ec2 associate-iam-instance-profile --instance-id {{ item.id }} --iam-instance-profile Name=DynamoDB-Admin"
  with_items: "{{ ec2.instances }}"

- name: Add new instance to host group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: launched
  with_items: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ ec2.instances }}"