- name: Install updates
  yum: name=* state=latest
  become: yes

- name: Setup nginx repo
  yum_repository:
    name: nginx
    description: NGINX Repo
    baseurl: http://nginx.org/packages/rhel/7/$basearch/
    gpgcheck: no
    enabled: yes
  become: yes

- name: Install packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - nginx
    - git
  become: yes

- name: Get Node.JS
  shell: curl --silent --location https://rpm.nodesource.com/setup_10.x | sudo bash -

- name: Install Node.JS
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - nodejs
    - gcc-c++
    - make
  become: yes

- name: Curl credentials
  shell: curl http://169.254.169.254/latest/meta-data/iam/security-credentials/DynamoDB-Admin

- name: Pull git repo
  git:
    repo: 'https://github.com/Just-Insane/FortuneSite.git'
    dest: /home/ec2-user/FortuneSite/
    version: master

- name: make server.js executable
  file:
    path: /home/ec2-user/FortuneSite/server.js
    owner: ec2-user
    group: ec2-user
    mode: 0775
  become: yes

- name: Setup FortuneSite Service
  copy:
    src: fortunesite.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Install dependancies
  shell: cd /home/ec2-user/FortuneSite/ && npm install

- name: Copy nginx conf file
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: yes

- name: Set selinux policy
  selinux:
    policy: targeted
    state: permissive
  become: yes

- service:
    name: fortunesite
    state: restarted
    enabled: yes
  become: yes

- service:
    name: nginx
    state: restarted
    enabled: yes
  become: yes

- shell: "curl {{ ansible_eth0.ipv4.address }} && sleep 10 && curl {{ ansible_eth0.ipv4.address }}"

- shell: cd /tmp && cat /var/log/audit/audit.log | audit2allow -a -M policy && semodule -i policy.pp && rm -f policy.*
  become: yes

- selinux:
    policy: targeted
    state: enforcing
  become: yes

- name: Restart FortuneSite Service
  service:
    name: fortunesite
    state: restarted
    enabled: yes
  become: yes

- name: Restart service nginx, if not running
  service:
    name: nginx
    state: restarted
    enabled: yes
  become: yes