- name: Install updates
  yum: name=* state=latest
  become: yes

- name: Install nginx
  yum: name=nginx state=latest
  become: yes

- name: Install git
  yum: name=git state=latest
  become: yes

- name: Allow web traffic 80
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 80
    ctstate: NEW
    jump: ACCEPT
    comment: Accept new port 80 connections.
  become: yes

- name: Allow new ssh connections
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    ctstate: NEW
    syn: match
    jump: ACCEPT
    comment: Accept new SSH connections.
  become: yes

- name: Allow related and established connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  become: yes

- name: Remove default nginx files
  file:
    state: absent
    path: /usr/share/nginx/html/
  become: yes

- name: Pull git repo
  git:
    repo: 'https://github.com/Just-Insane/FortuneSite.git'
    dest: /usr/share/nginx/html/
    version: master
  become: yes

- name: Set file permissions
  file:
    path: /usr/share/nginx/html
    owner: nginx
    recurse: yes
    group: nginx
    mode: 0664
  become: yes

- name: Start service nginx, if not running
  service:
    name: nginx
    state: restarted
    enabled: yes
  become: yes